### ISSUE TITLE
[Feature Request]: Create Level 2 - Divya's Journey Through Shapes

### ISSUE THREAD

**Issue by Captain-T2004** [bsoc-bitbyte/Dreamyard#3]
Description:
This is the second level of the game, focusing on the theme of shapes. The story continues with Divya, who, after learning about shapes at school, dreams about navigating through a room filled with various obstacles and hurdles.

Core Mechanic:
The main mechanic involves the player changing the shape of their character to overcome different obstacles. By pressing specific keys on the keyboard, the player can switch between shapes such as square, circle, triangle, and parallelogram. Each shape is suited to clearing certain types of hurdles, requiring the player to switch shapes strategically to progress.

Requirements:
- Assets:
  - Textures and models for the room and obstacles.
  - Character models for different shapes (square, circle, triangle, parallelogram).
  - Sound effects for shape changes and obstacle interactions.
  - Background music that complements the theme of shapes and exploration.
- Level Design:
  - Layout of the room with various obstacles and hurdles.
  - Design of the exit gate.
  - Implementation of shape-specific obstacles.
- Scripting:
  - Code for shape-changing mechanics.
  - Code for obstacle interactions and clearing mechanisms.
  - Code for triggering the exit gate upon clearing all hurdles.

Acceptance Criteria:
- The level must be fully playable, with the player able to change shapes and clear obstacles accordingly.
- All assets must be integrated and functioning correctly.
- The shape-changing mechanism should work smoothly, allowing the player to switch shapes as needed.
- The exit gate should only open after all hurdles are cleared.

Feel free to make creative changes and enhancements to the level design, art, and sound to ensure it aligns well with the overall game experience and provides an engaging and enjoyable challenge for the players. Your creativity and unique ideas are encouraged to make the level even more captivating.

**Comment by Palash3101** [comment]
@Captain-T2004, 
Can I work on this issue.
With the basic idea of changing the shape, using arrow keys, and each shape having some unique quality...
