### ISSUE TITLE
[Feature Request]: Create Pause Menu for Dreamyard

### ISSUE THREAD

**Issue by Captain-T2004** [bsoc-bitbyte/Dreamyard#9]
We need to implement a pause menu for our Dreamyard game in Unity. The pause menu should appear when the Escape button is pressed and should include the following buttons:

- Continue: Resumes the game from the current state.
- Main Menu: Returns the player to the main menu.

The Pause Menu should be consistent in all Levels

Requirements:
1. Pause Menu Activation:
   - The pause menu should appear when the Escape button is pressed.
   - The game should pause (freeze) while the pause menu is active.

2. Continue Button:
   - On clicking, it should resume the game from the current state.
   - Ensure the game unfreezes and all game elements return to their normal state.

3. Main Menu Button:
   - On clicking, it should return the player to the main menu.
   
Additional Notes:
- The pause menu should be visually consistent with the main menu and the game's overall art style.
- Ensure the buttons have appropriate hover and click effects to enhance user experience.
- The pause menu should be intuitive and accessible, allowing players to easily resume or exit the game.

**Comment by Palash3101** [comment]
I would like to work on this issue.
Using the canvas and its subsequent UI elements to create a working Pause Menu.
